Repository unosquare/passcore, pull requests merged in 2018-08, with the labels that each got.

#190 support expired passwords or passwords set to change at next login (#40)
  .gitignore
  src/Unosquare.PassCore.PasswordProvider/PasswordChangeProvider.cs
  src/Unosquare.PassCore.PasswordProvider/Unosquare.PassCore.PasswordProvider.csproj
Labels: bug

#196 Adding changes to implement pure LDAP provider
  Unosquare.PassCore.sln
  src/Unosquare.PassCore.Web/Startup.cs
  src/Unosquare.PassCore.Web/Unosquare.PassCore.Web.csproj
  src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeOptions.cs
  src/Zyborg.PassCore.PasswordProvider.LDAP/LdapPasswordChangeProvider.cs
  src/Zyborg.PassCore.PasswordProvider.LDAP/Win32ErrorCode.cs
  src/Zyborg.PassCore.PasswordProvider.LDAP/Zyborg.PassCore.PasswordProvider.LDAP.csproj
Labels: enhancement

#194 fetch settings before bootstrap the app to set language
  src/Unosquare.PassCore.Web/ClientApp/app/app.module.ts
  src/Unosquare.PassCore.Web/ClientApp/app/change-password/app.change-password.ts
  src/Unosquare.PassCore.Web/ClientApp/main.ts
  src/Unosquare.PassCore.Web/ClientApp/polyfills.ts
  src/Unosquare.PassCore.Web/package.json
  src/Unosquare.PassCore.Web/webpack.config.js
Labels: bug, help wanted
